version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
        - /feature\/.*/
    working_directory: ~/dao-server
    docker:
      - image: circleci/ruby:2.6.0-stretch
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dao_test
          MYSQL_USER: dao_user
          MYSQL_PASSWORD: digixtest
    steps:
      - checkout
      - type: cache-restore
        name: Restore bundle cache
        key: dao-server-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        name: Store bundle cache
        key: dao-server-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: bundle exec rake db:drop db:create db:migrate db:seed
      - run: bundle exec rake test
