development:
  adapter: async

staging:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: dao-server_production
