development: &defaults
  depth_limits:
    - 10
    - 5
    - 3

test:
  depth_limits:
    - 3
    - 2
    - 1

staging:
  depth_limits:
    - 10
    - 5
    - 3

production:
  depth_limits:
    - 10
    - 5
    - 3
