default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: dao_user

development:
  <<: *default
  database: dao_dev
  password: digixtest

test:
  <<: *default
  database: dao_test
  password: digixtest

staging:
  <<: *default
  database: dao_staging
  username: dao
  password: <%= ENV['DAO_STAGING_DATABASE_PASSWORD'] %>
  pool: 50
  timeout: 10000

production:
  <<: *default
  database: dao_production
  username: dao
  password: <%= ENV['DAO_PRODUCTION_DATABASE_PASSWORD'] %>
  pool: 128
  timeout: 10000

